version: '3'

services:

  backend:
    container_name: chybeta.apisix.demo1.backend
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    command: python3 server.py
    networks:
      apisix:

  apisix:
    image: apache/apisix:2.10.0-alpine
    container_name: chybeta.apisix.demo1.apisix
    restart: always
    volumes:
      - ./apisix/conf.yaml:/usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9080:9080/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    container_name: chybeta.apisix.demo1.etcd
    restart: always
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge