version: '3'

services:
  backend_server1:
    build: ./backend
    expose:
      - 8085
    command: python3 flask_backend.py

  httpd_mod_proxy:
    build: ./httpd_mod_proxy
    links:
      - backend_server1
    ports:
      - 80:80
