version: '3'

services:

  backend:
    container_name: chybeta.backend.demo1
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 gunicorn_demo:app --log-level DEBUG


  nginx:
    container_name: chybeta.nginx.demo1
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend