version: '3'

services:
  nginx:
    container_name: chybeta.nginx.demo5
    restart: always
    build: ./nginx
    ports:
      - "8000:8000"

  backend:
    container_name: chybeta.backend.demo5
    restart: always
    build: ./backend
    command: gunicorn -w 1 -b :5555 gunicorn_demo:app --log-level DEBUG
