version: '3'

services:
  backend_server1:
    build: ./backend
    expose:
      - 8000
#    command: node app.js
    command: python3 flask_pywsgi.py

  haproxy:
    image: haproxy:2.4.3-alpine
    volumes:
      - ./haproxy:/haproxy-override
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - backend_server1
    ports:
      - "80:8888"