version: '3'

services:

  backend:
    container_name: chybeta.backend.demo2
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    command: uvicorn --log-level debug --workers 1 --host 0.0.0.0 --port 8000 uvicorn_demo:app


  nginx:
    container_name: chybeta.nginx.demo2
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend